// Generated by CoffeeScript 1.10.0
(function() {
  var camelify, get_data, redraw,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  get_data = function(user_input) {
    var query;
    query = JSON.stringify({
      "luceneQuery": user_input
    });
    return d3.json('http://wafi.iit.cnr.it:33065/ClaviusWeb-1.0.2/ClaviusSearch/search').post(query, function(err, data) {
      return redraw(data);
    });
  };

  camelify = function(str) {
    var camel_str, char, index, j, len, upper_char_index;
    camel_str = "";
    upper_char_index = [];
    for (index = j = 0, len = str.length; j < len; index = ++j) {
      char = str[index];
      if (char === ['-']) {
        upper_char_index.push(index + 1);
      } else if (indexOf.call(upper_char_index, index) >= 0) {
        camel_str += char.toUpperCase();
      } else {
        camel_str += char;
      }
    }
    return camel_str;
  };

  d3.select('#search_panel input').on('keydown', function() {
    if (d3.event.keyCode === 13) {
      return get_data(this.value);
    }
  });

  d3.select('#search_button').on('click', function() {
    var user_input;
    user_input = d3.select('#search_panel input').node().value;
    return get_data(user_input);
  });

  redraw = function(data) {
    var aggregated_data, annotations, container, match, results, span;
    d3.select('#search_results').html("");
    container = d3.select('#search_results');
    aggregated_data = d3.nest().key(function(d) {
      return d.idDoc;
    }).entries(data);
    results = container.selectAll('.doc').data(aggregated_data);
    results.enter().append('div').attr({
      "class": 'doc'
    });
    span = results.append('div');
    span.append('div').attr({
      "class": 'id'
    }).text(function(d) {
      return "" + d.key;
    });
    span.append('a').attr({
      href: function(d) {
        return "http://claviusontheweb.it/dualView/?docId=" + (d.key.split('_')[1]);
      },
      target: '_blank'
    }).append('img').attr({
      src: function(d) {
        return "http://claviusontheweb.it/exist/rest/db/clavius/documents/" + (d.key.split('_')[1]) + "/thumbnail.jpg";
      },
      title: 'Visualize the manuscript'
    });
    match = results.append('div').attr({
      "class": 'annotations'
    });
    annotations = match.selectAll('.annotation').data(function(d) {
      return d.values;
    });
    annotations.enter().append('div').attr({
      "class": 'annotation'
    });
    annotations.append('div').attr({
      "class": 'match'
    }).html(function(d) {
      return "..." + (d.leftContext.replace(/\n/g, '<br>')) + " <span class='matched'>" + (d.matched.replace(/\n/g, '<br>')) + "</span> " + (d.rightContext.replace(/\n/g, '<br>')) + "...";
    });
    annotations.append('div').attr({
      "class": 'concepts'
    }).html(function(d) {
      if (d.concept === '') {
        return '';
      } else {
        return '(' + (d.concept.split(' ').map(function(c, i) {
          return (i > 0 ? ', ' : '') + "<span class='concept'>" + (camelify(c)) + "</span>";
        }).slice(0, -1).join('')) + ')';
      }
    });
    return d3.selectAll('.concept').on('click', function(d) {
      d3.select('#search_panel input').node().value = "concept:" + this.textContent;
      return get_data("concept:" + this.textContent);
    });
  };

}).call(this);
