// Generated by CoffeeScript 1.10.0
(function() {
  var camelify, clavius_search, redraw_concepts, redraw_docs, wikidata_search,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  d3.select('#search input').on('keydown', function() {
    if (d3.event.keyCode === 13) {
      return wikidata_search(this.value);
    }
  });

  d3.select('#search_button').on('click', function() {
    var user_input;
    user_input = d3.select('#search input').node().value;
    return wikidata_search(user_input);
  });

  wikidata_search = function(user_input) {
    return d3.json("api/wikidata.php?text=" + user_input, function(err_1, wd_data) {
      var index, query;
      query = JSON.stringify(wd_data.map(function(d) {
        return {
          uri: "http://www.wikidata.org/entity/" + d.id
        };
      }));
      index = {};
      wd_data.forEach(function(d) {
        return index[d.id] = d;
      });
      return d3.json("http://wafi.iit.cnr.it:33065/ClaviusWeb-1.0.3/ClaviusSearch/count").post(query, function(err_2, cs_data) {
        return redraw_concepts((cs_data.filter(function(d) {
          return d.count > 0;
        })).map(function(d) {
          index[d.uri.split('/').slice(-1)].count = d.count;
          return index[d.uri.split('/').slice(-1)];
        }));
      });
    });
  };

  clavius_search = function(uri) {
    var query;
    query = '{luceneQuery: "concept:\\"' + uri + '\\""}';
    return d3.json('http://wafi.iit.cnr.it:33065/ClaviusWeb-1.0.3/ClaviusSearch/search').post(query, function(err, results) {
      var result_docs, result_docs_index;
      result_docs = d3.nest().key(function(d) {
        return d.idNeo4j;
      }).entries(results);
      result_docs_index = {};
      result_docs.forEach(function(d) {
        return result_docs_index[parseInt(d.key)] = d;
      });
      return d3.json("api/get_docs_by_index_ids.php?index_ids=[" + (result_docs.map(function(d) {
        return d.key;
      }).join(',')) + "]", function(docs) {
        docs.forEach(function(d) {
          return result_docs_index[d.node.index_id].doc = d;
        });
        return redraw_docs(result_docs);
      });
    });
  };

  camelify = function(str) {
    var camel_str, char, i, index, len, upper_char_index;
    camel_str = "";
    upper_char_index = [];
    for (index = i = 0, len = str.length; i < len; index = ++i) {
      char = str[index];
      if (char === ['-']) {
        upper_char_index.push(index + 1);
      } else if (indexOf.call(upper_char_index, index) >= 0) {
        camel_str += char.toUpperCase();
      } else {
        camel_str += char;
      }
    }
    return camel_str;
  };

  redraw_concepts = function(data) {
    var enter_results, resource, results;
    d3.select('#concepts .counter').remove();
    d3.select('#concepts').append('div').attr({
      "class": 'counter'
    }).text(function(d) {
      return data.length + " " + (data.length === 1 ? 'Concept' : 'Concepts') + " found.";
    });
    results = d3.select('#concepts').selectAll('.concept').data(data, function(d) {
      return d.concepturi;
    });
    enter_results = results.enter().append('div').attr({
      "class": 'concept'
    }).on('click', function(d) {
      return clavius_search(d.concepturi);
    });
    results.order();
    enter_results.append('div').attr({
      "class": 'icon'
    }).append('i').attr({
      "class": 'fa fa-circle-o',
      'aria-hidden': 'true'
    });
    resource = enter_results.append('div').attr({
      "class": 'resource'
    });
    resource.append('span').attr({
      "class": 'label'
    }).text(function(d) {
      return d.label;
    });
    resource.append('span').html(function(d) {
      return " (<a target='_blank' class='link' href='" + d.concepturi + "'>wd:" + d.id + "</a>)";
    });
    resource.append('div').attr({
      "class": 'description'
    }).text(function(d) {
      return d.description;
    });
    resource.append('div').attr({
      "class": 'count'
    }).text(function(d) {
      return d.count + " " + (d.count === 1 ? 'Occurrence' : 'Occurrences') + " found.";
    });

    /*count = enter_results.append 'div'
      .attr
        class: 'count'
      .text (d) -> d.count
     */
    return results.exit().remove();
  };

  redraw_docs = function(data) {
    var annotations, container, match, results, right_container;
    container = d3.select('#docs');
    container.html("");
    container.append('div').attr({
      "class": 'counter'
    }).text(function(d) {
      return data.length + " " + (data.length === 1 ? 'Document' : 'Documents') + " found.";
    });
    results = container.selectAll('.doc').data(data);
    results.enter().append('div').attr({
      "class": 'doc'
    });
    results.append('div').attr({
      "class": 'icon'
    }).append('i').attr({
      "class": 'fa fa-file-o',
      'aria-hidden': 'true'
    });
    right_container = results.append('div');
    right_container.append('div').attr({
      "class": 'label'
    }).append('a').attr({
      href: function(d) {
        return "http://wafi.iit.cnr.it/webvis/dev/tea_nitaku/#docs/" + d.doc.id;
      }
    }).text(function(d) {
      return d.doc.node.label;
    });
    match = right_container.append('div').attr({
      "class": 'annotations'
    });
    annotations = match.selectAll('.annotation').data(function(d) {
      return d.values;
    });
    annotations.enter().append('div').attr({
      "class": 'annotation'
    });
    return annotations.html(function(d) {
      return "..." + (d.leftContext.replace(/\n/g, '<br>')) + " <span class='matched'>" + (d.matched.replace(/\n/g, '<br>')) + "</span> " + (d.rightContext.replace(/\n/g, '<br>')) + "...";
    });
  };

}).call(this);
