// Generated by CoffeeScript 1.10.0
(function() {
  var mkdir, neo;

  neo = require('/var/www/folders/api/neo.js');

  mkdir = function(cwd_id, label) {
    return neo.cypher({
      query: "MATCH (cwd) WHERE id(cwd) = " + cwd_id + " CREATE (cwd)-[r:SUBNODE]->(n:AuxFolder {label: '" + label + "'}) RETURN n;",
      callback: function(error, data) {
        if (error) {
          throw error;
        }
        return write('');
      }
    });
  };

  if ((request.query.cwd_id == null) || (request.query.label == null)) {
    throw new Error('Both cwd_id and label must be specified in order to execute mkdir function.');
  } else {
    mkdir(request.query.cwd_id, request.query.label);
  }

}).call(this);
