// Generated by CoffeeScript 1.10.0
(function() {
  var as_objects, cypher, request, txUrl;

  request = require("request");

  txUrl = 'http://localhost:7474/db/data/transaction/commit';

  cypher = function(conf) {
    var callback, params, query;
    query = conf.query;
    params = conf.params != null ? conf.params : {};
    callback = conf.callback;
    return request.post({
      uri: txUrl,
      json: {
        statements: [
          {
            statement: query,
            parameters: params
          }
        ]
      }
    }, function(error, response) {
      return callback(error, response.body);
    });
  };

  as_objects = function(data) {
    if (data.errors.length > 0) {
      throw JSON.stringify(data.errors);
    }
    return data.results[0].data.map(function(d) {
      var o;
      o = {};
      d.row.forEach(function(p, i) {
        return o[data.results[0].columns[i]] = d.row[i];
      });
      return o;
    });
  };

  exports.cypher = cypher;

  exports.as_objects = as_objects;

}).call(this);
