// Generated by CoffeeScript 1.10.0
(function() {
  var neo, remove;

  response.headers['Content-Type'] = 'application/json';

  neo = require('/var/www/folders/api/neo.js');

  remove = function(_id) {
    return neo.cypher({
      query: "START n=node(785) OPTIONAL MATCH (n)-[r]-() DELETE r,n;",
      callback: function(error, data) {
        if (error) {
          throw error;
        }
        return write(JSON.stringify(neo.as_objects(data)));
      }
    });
  };

  if (request.query.id == null) {
    throw 'The id of a node must be specified in order to execute the remove function.';
  } else {
    remove(request.query.id);
  }

}).call(this);
